const std = @import("std");

pub const RequiredLibrary = enum {
    /// Use the system provided library
    system,
    /// Use imgz's bundled version of the library
    bundled,
    /// A custom library will be linked manually
    custom,
    /// Don't link to the library
    disabled,
};

pub const LazyFileEditor = struct {
    step: std.Build.Step,
    wf: *std.Build.Step.WriteFile,
    source_file: std.Build.LazyPath,
    basename: []const u8,
    result: std.Build.LazyPath,
    editor_fn: *const fn (source_contents: []const u8, out_writer: *std.Io.Writer) anyerror!void,

    pub fn create(
        b: *std.Build,
        path: std.Build.LazyPath,
        basename: []const u8,
        editor_fn: *const fn (source_contents: []const u8, out_writer: *std.Io.Writer) anyerror!void,
    ) *LazyFileEditor {
        const self = b.allocator.create(LazyFileEditor) catch @panic("OOM");
        const wf = b.addWriteFiles();
        const dest_file = wf.getDirectory().path(b, basename);
        self.* = .{
            .step = std.Build.Step.init(.{
                .id = .custom,
                .name = "Lazy File Editor",
                .owner = b,
                .makeFn = make,
            }),
            .wf = wf,
            .basename = b.dupe(basename),
            .source_file = path,
            .result = dest_file,
            .editor_fn = editor_fn,
        };
        wf.step.dependOn(&self.step);
        return self;
    }

    fn make(step: *std.Build.Step, _: std.Build.Step.MakeOptions) !void {
        const self: *@This() = @fieldParentPtr("step", step);
        const b = step.owner;

        const source_file_path = try self.source_file.getPath3(b, step).toString(b.allocator);
        defer b.allocator.free(source_file_path);

        const source_file_contents = try std.fs.cwd().readFileAlloc(b.allocator, source_file_path, std.math.maxInt(usize));
        defer b.allocator.free(source_file_contents);

        var dest_writer = std.Io.Writer.Allocating.init(b.allocator);
        defer dest_writer.deinit();

        try self.editor_fn(source_file_contents, &dest_writer.writer);
        try dest_writer.writer.flush();

        const dest_file_contents = dest_writer.written();
        _ = self.wf.add(self.basename, dest_file_contents);
    }
};

pub const AndroidUtils = struct {
    pub fn getAndroidTriple(target: std.Target) error{InvalidAndroidTarget}![]const u8 {
        if (target.abi != .android and target.abi != .androideabi) return error.InvalidAndroidTarget;
        return switch (target.cpu.arch) {
            .x86 => "i686-linux-android",
            .x86_64 => "x86_64-linux-android",
            .arm => "arm-linux-androideabi",
            .aarch64 => "aarch64-linux-android",
            .riscv64 => "riscv64-linux-android",
            else => error.InvalidAndroidTarget,
        };
    }

    pub fn createLibC(b: *std.Build, system_target: []const u8, android_api_version: u32, ndk_sysroot_path: []const u8, ndk_version: []const u8) std.Build.LazyPath {
        const libc_file_format =
            \\# Generated by zig-android-sdk. DO NOT EDIT.
            \\
            \\# The directory that contains `stdlib.h`.
            \\# On POSIX-like systems, include directories be found with: `cc -E -Wp,-v -xc /dev/null`
            \\include_dir={[include_dir]s}
            \\
            \\# The system-specific include directory. May be the same as `include_dir`.
            \\# On Windows it's the directory that includes `vcruntime.h`.
            \\# On POSIX it's the directory that includes `sys/errno.h`.
            \\sys_include_dir={[sys_include_dir]s}
            \\
            \\# The directory that contains `crt1.o`.
            \\# On POSIX, can be found with `cc -print-file-name=crt1.o`.
            \\# Not needed when targeting MacOS.
            \\crt_dir={[crt_dir]s}
            \\
            \\# The directory that contains `vcruntime.lib`.
            \\# Only needed when targeting MSVC on Windows.
            \\msvc_lib_dir=
            \\
            \\# The directory that contains `kernel32.lib`.
            \\# Only needed when targeting MSVC on Windows.
            \\kernel32_lib_dir=
            \\
            \\gcc_dir=
        ;

        const include_dir = b.fmt("{s}/usr/include", .{ndk_sysroot_path});
        const sys_include_dir = b.fmt("{s}/usr/include/{s}", .{ ndk_sysroot_path, system_target });
        const crt_dir = b.fmt("{s}/usr/lib/{s}/{d}", .{ ndk_sysroot_path, system_target, android_api_version });

        const libc_file_contents = b.fmt(libc_file_format, .{
            .include_dir = include_dir,
            .sys_include_dir = sys_include_dir,
            .crt_dir = crt_dir,
        });

        const filename = b.fmt("android-libc_target-{s}_version-{d}_ndk-{s}.conf", .{ system_target, android_api_version, if (ndk_version.len > 0) ndk_version else "unknown" });

        const write_file = b.addWriteFiles();
        const android_libc_path = write_file.add(filename, libc_file_contents);
        return android_libc_path;
    }
};
