name: Build and Test
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: Install nasm (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm

      - name: Build Libraries
        run: |
          zig build ci -Doptimize=ReleaseFast --summary all --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zig-out
          path: zig-out/

  test:
    name: Run Tests (all configs on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: Install nasm (Linux)
        if: contains(matrix.target, 'x86_64') && runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm

      - name: Install nasm (macOS)
        if: contains(matrix.target, 'x86_64') && runner.os == 'macOS'
        run: |
          brew install nasm

      - name: Install nasm (Windows)
        if: contains(matrix.target, 'x86_64') && runner.os == 'Windows'
        run: |
          choco install -y nasm

      - name: Run tests (All enabled)
        run: |
          zig build test --summary all --verbose

      - name: Run tests (Only spng)
        run: |
          zig build test -Dspng=true -Djpeg_turbo=false -Dtiff=false -Dwebp=false --summary all --verbose

      - name: Run tests (Only jpeg-turbo)
        run: |
          zig build test -Dspng=false -Djpeg_turbo=true -Dtiff=false -Dwebp=false --summary all --verbose

      - name: Run tests (Only tiff)
        run: |
          zig build test -Dspng=false -Djpeg_turbo=false -Dtiff=true -Dwebp=false --summary all --verbose

      - name: Run tests (Only webp)
        run: |
          zig build test -Dspng=false -Djpeg_turbo=false -Dtiff=false -Dwebp=true --summary all --verbose

